// MAE 1.0 - THIS FILE WAS GERNERATED AUTOMATICALY

#include "place_recognition.h"

void build_network (void)
{
NUM_ISOLATE_NEURON_LAYERS = 10;
NUM_INPUTS = 1;
NUM_OUTPUTS = 4;
NUM_FILTERS = 3;
srand (5); 
memset((void *) &(nl_v1_pattern), 0, sizeof(NEURON_LAYER));
nl_v1_pattern.name = "nl_v1_pattern";
memset((void *) &(in_pattern_gaussian), 0, sizeof(NEURON_LAYER));
in_pattern_gaussian.name = "in_pattern_gaussian";
memset((void *) &(in_pattern_translated), 0, sizeof(NEURON_LAYER));
in_pattern_translated.name = "in_pattern_translated";
memset((void *) &(in_pattern_cropped), 0, sizeof(NEURON_LAYER));
in_pattern_cropped.name = "in_pattern_cropped";
memset((void *) &(recall), 0, sizeof(NEURON_LAYER));
recall.name = "recall";
memset((void *) &(in_pattern), 0, sizeof(INPUT_DESC));
in_pattern.name = "in_pattern";
memset((void *) &(out_recall), 0, sizeof(OUTPUT_DESC));
out_recall.name = "out_recall";
memset((void *) &(out_in_pattern_cropped), 0, sizeof(OUTPUT_DESC));
out_in_pattern_cropped.name = "out_in_pattern_cropped";
memset((void *) &(out_in_pattern_gaussian), 0, sizeof(OUTPUT_DESC));
out_in_pattern_gaussian.name = "out_in_pattern_gaussian";
memset((void *) &(out_nl_v1_pattern), 0, sizeof(OUTPUT_DESC));
out_nl_v1_pattern.name = "out_nl_v1_pattern";

__line = 3;
NEURON_MEMORY_SIZE = 3783;
__line = 4;
TYPE_SHOW = SHOW_FRAME;
__line = 5;
TYPE_MOVING_FRAME = STOP;
__line = 12;
//;
__line = 13;
//;
__line = 14;
//;
__line = 16;
//;
__line = 17;
//;
__line = 19;
//;
__line = 20;
//;
__line = 22;
translation_filter_deltaX = IMAGE_WIDTH / 2.0;
__line = 23;
translation_filter_deltaY = IMAGE_HEIGHT / 2.0;
__line = 25;
//;
__line = 26;
//;
__line = 28;
//;
__line = 29;
//;
__line = 33;
create_neuron_layer (&nl_v1_pattern, &minchinton, COLOR, GREYSCALE, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 35;
create_neuron_layer (&in_pattern_gaussian, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH,IMAGE_HEIGHT_CROP,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 37;
create_neuron_layer (&in_pattern_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH,IMAGE_HEIGHT_CROP,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 39;
create_neuron_layer (&in_pattern_cropped, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH,IMAGE_HEIGHT_CROP,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 41;
create_neuron_layer (&recall, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH,IMAGE_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 45;
create_output (&out_recall, IMAGE_WIDTH,IMAGE_HEIGHT, NULL, 0);
__line = 47;
create_output (&out_in_pattern_cropped, IMAGE_WIDTH,IMAGE_HEIGHT_CROP, NULL, 0);
__line = 49;
create_output (&out_in_pattern_gaussian, IMAGE_WIDTH,IMAGE_HEIGHT_CROP, NULL, 0);
__line = 51;
create_output (&out_nl_v1_pattern, NL_WIDTH,NL_HEIGHT, output_handler, "%s", "out_recall");
__line = 55;
create_input (&in_pattern, IMAGE_WIDTH,IMAGE_HEIGHT, COLOR, 0, REGULAR_PYRAMID, input_generator, input_controler, " ", " ");
__line = 60;
create_filter (crop_nl_filter, &in_pattern_cropped, 1, in_pattern.neuron_layer, "%d %d", 0, 16);
__line = 63;
create_filter (translate_nl_filter, &in_pattern_translated, 1, &in_pattern_cropped, "%p %p", &translation_filter_deltaX, &translation_filter_deltaY);
__line = 66;
create_filter (gaussian_filter, &in_pattern_gaussian, 1, &in_pattern_translated, "%d %f", 33, 11.0);
__line = 70;
output_connect (&recall, &out_recall);
__line = 72;
output_connect (&in_pattern_cropped, &out_in_pattern_cropped);
__line = 74;
output_connect (&in_pattern_gaussian, &out_in_pattern_gaussian);
__line = 76;
output_connect (&nl_v1_pattern, &out_nl_v1_pattern);
__line = 80;
connect_neurons (RAN, &in_pattern_translated, &nl_v1_pattern, INPUTS_PER_NEURON, 0, 0, 0,-1,-1,-1,-1, -1,-1,-1,-1,STANDARD_INTERCONNECTION_PATTERN);
__line = 81;
connect_neurons (GAU, &in_pattern_translated, &nl_v1_pattern, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, 0, 0, -1,-1,-1,-1, -1,-1,-1,-1, DIFFERENT_INTERCONNECTION_PATTERN);
__line = 85;
associate_neurons (&nl_v1_pattern, &nl_v1_pattern);
__line = 89;
create_interpreter_user_function (INT_TYPE, set_network_status, "set_network_status", "%d");
;
__line = 90;
create_interpreter_user_function (INT_TYPE, get_frame, "get_frame", "%d");
;
__line = 91;
create_interpreter_user_function (INT_TYPE, read_dataset, "read_dataset", "%d");
;
__line = 92;
create_interpreter_user_function (INT_TYPE, randomize, "randomize", "%p %d %d");
;
__line = 93;
create_interpreter_user_function (INT_TYPE, set_network_evaluate, "set_network_evaluate", "%d");
;
map_layers2id (); 
count_num_neurons (); 
initialise_memory (); 
create_io_windows (); 
}
