#!/bin/bash
export LC_ALL="en_US"
current_date=$1
week_day=`date --date="$current_date" +%A`
while [[ $week_day != "Wednesday" ]]; do
	current_date=`date --date="$current_date - 1 day" +%F`
	week_day=`date --date="$current_date" +%A`
done
echo $current_date
