// MAE 1.0 - THIS FILE WAS GERNERATED AUTOMATICALY

#include "face_recog.h"

void build_network (void)
{
NUM_ISOLATE_NEURON_LAYERS = 3;
NUM_INPUTS = 1;
NUM_OUTPUTS = 3;
NUM_FILTERS = 2;
srand (5); 
nl_face_recog_lp.name = "nl_face_recog_lp";
nl_face_recog_lp_f.name = "nl_face_recog_lp_f";
nl_landmark.name = "nl_landmark";
face_recog.name = "face_recog";
out_face_recog_lp.name = "out_face_recog_lp";
out_face_recog_lp_f.name = "out_face_recog_lp_f";
out_landmark.name = "out_landmark";

__line = 2;
NEURON_MEMORY_SIZE = 700;
__line = 4;
TYPE_SHOW = SHOW_FRAME;
__line = 5;
TYPE_MOVING_FRAME = STOP;
__line = 8;
//;
__line = 9;
//;
__line = 11;
//;
__line = 12;
//;
__line = 14;
//;
__line = 17;
//;
__line = 18;
//;
__line = 23;
//;
__line = 24;
//;
__line = 25;
//;
__line = 26;
//;
__line = 28;
//;
__line = 32;
create_neuron_layer (&nl_face_recog_lp, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT);
__line = 33;
create_neuron_layer (&nl_face_recog_lp_f, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT);
__line = 34;
create_neuron_layer (&nl_landmark, &minchinton, COLOR, GREYSCALE, OUT_WIDTH,OUT_HEIGHT);
__line = 37;
create_output (&out_face_recog_lp, NL_WIDTH,NL_HEIGHT, NULL, 0);
__line = 38;
create_output (&out_face_recog_lp_f, NL_WIDTH,NL_HEIGHT, NULL, 0);
__line = 39;
create_output (&out_landmark, OUT_WIDTH,OUT_HEIGHT, output_handler, " ");
__line = 42;
create_input (&face_recog, INPUT_WIDTH,INPUT_HEIGHT, COLOR, 0, REGULAR_PYRAMID, input_generator, input_controler, " ", " ");
__line = 46;
create_filter (face_reshape_filter2, &nl_face_recog_lp, 1, face_recog.neuron_layer, "%f %f %f %f", BASELINE_FACTOR, X_OFFSET, Y_OFFSET, GAUSSIAN_SIGMA);
__line = 51;
create_filter (gaussian_filter, &nl_face_recog_lp_f, 1, &nl_face_recog_lp, "%d %f", 5, 1.0);
__line = 54;
output_connect (&nl_face_recog_lp, &out_face_recog_lp);
__line = 55;
output_connect (&nl_face_recog_lp_f, &out_face_recog_lp_f);
__line = 56;
output_connect (&nl_landmark, &out_landmark);
__line = 59;
associate_neurons (&nl_landmark, &nl_landmark);
__line = 64;
connect_neurons (GAU, &nl_face_recog_lp_f, &nl_landmark, SYNAPSES, 10.0, -1,-1,-1,-1, -1,-1,-1,-1);
__line = 67;
create_interpreter_user_function (INT_TYPE, GetFace, "GetFace", "%d %d %d");
;
__line = 68;
create_interpreter_user_function (INT_TYPE, GetRandomFace, "GetRandomFace", "%d");
;
__line = 69;
create_interpreter_user_function (INT_TYPE, Move2Eye, "Move2Eye", "%d");
;
__line = 70;
create_interpreter_user_function (INT_TYPE, Move2Nose, "Move2Nose", "%d");
;
__line = 71;
create_interpreter_user_function (INT_TYPE, Move2Nose2, "Move2Nose2", "%d %d");
;
__line = 72;
create_interpreter_user_function (INT_TYPE, Move2Mouth, "Move2Mouth", "%d");
;
__line = 73;
create_interpreter_user_function (INT_TYPE, ShowStatistics, "ShowStatistics", "%d");
;
__line = 74;
create_interpreter_user_function (INT_TYPE, ResetStatistics, "ResetStatistics", "%d");
;
__line = 75;
create_interpreter_user_function (INT_TYPE, SetNetworkStatus, "SetNetworkStatus", "%d");
;
__line = 76;
create_interpreter_user_function (INT_TYPE, SetNetworkStatus2, "SetNetworkStatus2", "%d %d");
;
map_layers2id (); 
count_num_neurons (); 
initialise_memory (); 
create_io_windows (); 
}
