./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
./wnn_pred teste.cml
