compile:
	gcc -o stimulus_generator stimulus_generator.c -I/home/stiven/MAE/include -L/usr/local/lib -L/usr/X11R6/lib -L/home/stiven/MAE/lib -lnet_conn -lGA -lXmu -lXext -lX11 -ltiff -lglut -lGLU -lGL -lXi -lforms -lm -lfl -g
clean: 
	rm -rf stimulus_generator
	
