// MAE 1.0 - THIS FILE WAS GERNERATED AUTOMATICALY

#include "visual_search.h"

void build_network (void)
{
NUM_ISOLATE_NEURON_LAYERS = 34;
NUM_INPUTS = 1;
NUM_OUTPUTS = 10;
NUM_FILTERS = 14;
srand (5); 
memset((void *) &(nl_v1_activation_map), 0, sizeof(NEURON_LAYER));
nl_v1_activation_map.name = "nl_v1_activation_map";
memset((void *) &(nl_v1_activation_map_neuron_weight), 0, sizeof(NEURON_LAYER));
nl_v1_activation_map_neuron_weight.name = "nl_v1_activation_map_neuron_weight";
memset((void *) &(nl_v1_activation_map_neuron_weight_thresholded), 0, sizeof(NEURON_LAYER));
nl_v1_activation_map_neuron_weight_thresholded.name = "nl_v1_activation_map_neuron_weight_thresholded";
memset((void *) &(nl_target_coordinates), 0, sizeof(NEURON_LAYER));
nl_target_coordinates.name = "nl_target_coordinates";
memset((void *) &(nl_v1_pattern), 0, sizeof(NEURON_LAYER));
nl_v1_pattern.name = "nl_v1_pattern";
memset((void *) &(in_pattern_translated), 0, sizeof(NEURON_LAYER));
in_pattern_translated.name = "in_pattern_translated";
memset((void *) &(in_pattern_filtered_translated), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated.name = "in_pattern_filtered_translated";
memset((void *) &(in_pattern_filtered_translated_red), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_red.name = "in_pattern_filtered_translated_red";
memset((void *) &(in_pattern_filtered_translated_green), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_green.name = "in_pattern_filtered_translated_green";
memset((void *) &(in_pattern_filtered_translated_blue), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_blue.name = "in_pattern_filtered_translated_blue";
memset((void *) &(table), 0, sizeof(NEURON_LAYER));
table.name = "table";
memset((void *) &(table_v1), 0, sizeof(NEURON_LAYER));
table_v1.name = "table_v1";
memset((void *) &(nl_activation_map_hough), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough.name = "nl_activation_map_hough";
memset((void *) &(nl_activation_map_hough_gaussian), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_gaussian.name = "nl_activation_map_hough_gaussian";
memset((void *) &(nl_activation_map_hough_v1), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_v1.name = "nl_activation_map_hough_v1";
memset((void *) &(nl_activation_map_hough_zoom), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_zoom.name = "nl_activation_map_hough_zoom";
memset((void *) &(nl_activation_map_hough_zoom_gaussian), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_zoom_gaussian.name = "nl_activation_map_hough_zoom_gaussian";
memset((void *) &(in_pattern), 0, sizeof(INPUT_DESC));
in_pattern.name = "in_pattern";
memset((void *) &(nl_v1_activation_map_neuron_weight_thresholded_out), 0, sizeof(OUTPUT_DESC));
nl_v1_activation_map_neuron_weight_thresholded_out.name = "nl_v1_activation_map_neuron_weight_thresholded_out";
memset((void *) &(nl_v1_pattern_out), 0, sizeof(OUTPUT_DESC));
nl_v1_pattern_out.name = "nl_v1_pattern_out";
memset((void *) &(table_v1_out), 0, sizeof(OUTPUT_DESC));
table_v1_out.name = "table_v1_out";
memset((void *) &(out_v1_activation_map), 0, sizeof(OUTPUT_DESC));
out_v1_activation_map.name = "out_v1_activation_map";
memset((void *) &(out_nl_v1_activation_map_neuron_weight_thresholded), 0, sizeof(OUTPUT_DESC));
out_nl_v1_activation_map_neuron_weight_thresholded.name = "out_nl_v1_activation_map_neuron_weight_thresholded";
memset((void *) &(out_target_coordinates), 0, sizeof(OUTPUT_DESC));
out_target_coordinates.name = "out_target_coordinates";
memset((void *) &(out_in_pattern_filtered_translated), 0, sizeof(OUTPUT_DESC));
out_in_pattern_filtered_translated.name = "out_in_pattern_filtered_translated";
memset((void *) &(out_table), 0, sizeof(OUTPUT_DESC));
out_table.name = "out_table";
memset((void *) &(out_nl_activation_map_hough_zoom), 0, sizeof(OUTPUT_DESC));
out_nl_activation_map_hough_zoom.name = "out_nl_activation_map_hough_zoom";
memset((void *) &(out_nl_activation_map_hough_zoom_gaussian), 0, sizeof(OUTPUT_DESC));
out_nl_activation_map_hough_zoom_gaussian.name = "out_nl_activation_map_hough_zoom_gaussian";

__line = 3;
TYPE_SHOW = SHOW_FRAME;
__line = 4;
TYPE_MOVING_FRAME = STOP;
__line = 24;
//;
__line = 25;
//;
__line = 28;
//;
__line = 29;
//;
__line = 30;
//;
__line = 31;
//;
__line = 32;
//;
__line = 33;
//;
__line = 34;
//;
__line = 35;
//;
__line = 36;
//;
__line = 37;
//;
__line = 38;
//;
__line = 39;
//;
__line = 42;
//;
__line = 43;
//;
__line = 45;
//;
__line = 46;
//;
__line = 49;
NEURON_MEMORY_SIZE = 32 * NL_WIDTH * NL_HEIGHT;
__line = 51;
//;
__line = 52;
//;
__line = 53;
//;
__line = 55;
//;
__line = 58;
//;
__line = 59;
//;
__line = 62;
//;
__line = 65;
translation_filter_deltaX = IMAGE_WIDTH / 2.0;
__line = 66;
translation_filter_deltaY = IMAGE_HEIGHT / 2.0;
__line = 69;
g_kernel_size = 5;
__line = 70;
g_sigma = 1.0;
__line = 73;
//;
__line = 76;
HIGHEST_OUTPUT = 1.0;
__line = 79;
//;
__line = 81;
NEURON_MEMORY_INDEX_SIZE = 10;
__line = 87;
create_neuron_layer (&nl_v1_activation_map, &minchinton, COLOR_SELECTIVE, COLOR, NL_WIDTH,NL_HEIGHT,SHARED_MEMORY, NEURON_MEMORY_SIZE);
__line = 90;
create_neuron_layer (&nl_v1_activation_map_neuron_weight, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 91;
create_neuron_layer (&nl_v1_activation_map_neuron_weight_thresholded, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
create_output (&nl_v1_activation_map_neuron_weight_thresholded_out, NL_WIDTH,NL_HEIGHT, NULL, 0);
output_connect (&nl_v1_activation_map_neuron_weight_thresholded, &nl_v1_activation_map_neuron_weight_thresholded_out);
__line = 93;
create_neuron_layer (&nl_target_coordinates, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, 2,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 95;
create_neuron_layer (&nl_v1_pattern, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
create_output (&nl_v1_pattern_out, NL_WIDTH,NL_HEIGHT, NULL, 0);
output_connect (&nl_v1_pattern, &nl_v1_pattern_out);
__line = 97;
create_neuron_layer (&in_pattern_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 99;
create_neuron_layer (&in_pattern_filtered_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 100;
create_neuron_layer (&in_pattern_filtered_translated_red, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 101;
create_neuron_layer (&in_pattern_filtered_translated_green, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 102;
create_neuron_layer (&in_pattern_filtered_translated_blue, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 104;
create_neuron_layer (&table, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 105;
create_neuron_layer (&table_v1, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
create_output (&table_v1_out, NL_WIDTH,NL_HEIGHT, NULL, 0);
output_connect (&table_v1, &table_v1_out);
__line = 107;
create_neuron_layer (&nl_activation_map_hough, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 108;
create_neuron_layer (&nl_activation_map_hough_gaussian, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 109;
create_neuron_layer (&nl_activation_map_hough_v1, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 111;
create_neuron_layer (&nl_activation_map_hough_zoom, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, TAM_NL_ZOOM,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 112;
create_neuron_layer (&nl_activation_map_hough_zoom_gaussian, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, TAM_NL_ZOOM,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 118;
create_output (&out_v1_activation_map, NL_WIDTH,NL_HEIGHT, NULL, 0);
__line = 120;
create_output (&out_nl_v1_activation_map_neuron_weight_thresholded, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, output_handler_weighted_average_value_position, "%s %f", TARGET_NEURON_LAYER_NAME, LOG_FACTOR);
__line = 122;
create_output (&out_target_coordinates, 2,1, NULL, 0);
__line = 124;
create_output (&out_in_pattern_filtered_translated, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, NULL, 0);
__line = 126;
create_output (&out_table, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, NULL, 0);
__line = 128;
create_output (&out_nl_activation_map_hough_zoom, TAM_NL_ZOOM,1, output_handler_resize, "%f", LOG_FACTOR);
__line = 130;
create_output (&out_nl_activation_map_hough_zoom_gaussian, TAM_NL_ZOOM,1, output_handler_resize, "%f", LOG_FACTOR);
__line = 136;
create_input (&in_pattern, IMAGE_WIDTH,IMAGE_HEIGHT, COLOR, 0, REGULAR_PYRAMID, input_generator, input_controler, " ", " ");
__line = 143;
create_filter (translate_nl_filter, &in_pattern_translated, 1, in_pattern.neuron_layer, "%p %p", &translation_filter_deltaX, &translation_filter_deltaY);
__line = 146;
create_filter (gaussian_filter, &in_pattern_filtered_translated, 1, &in_pattern_translated, "%d %f", 5, 1.0);
__line = 148;
create_filter (red_mask_filter, &in_pattern_filtered_translated_red, 1, &in_pattern_filtered_translated, "");
__line = 149;
create_filter (green_mask_filter, &in_pattern_filtered_translated_green, 1, &in_pattern_filtered_translated, "");
__line = 150;
create_filter (blue_mask_filter, &in_pattern_filtered_translated_blue, 1, &in_pattern_filtered_translated, "");
__line = 153;
create_filter (map_image_v1, &nl_v1_pattern, 1, &in_pattern_filtered_translated, "%s %f", "", LOG_FACTOR);
__line = 155;
create_filter (map_image_v1, &table_v1, 1, &table, "%s %f", "", LOG_FACTOR);
__line = 157;
create_filter (compute_weigheted_neighboor_filter, &nl_v1_activation_map_neuron_weight, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 159;
create_filter (threshold_cut_filter, &nl_v1_activation_map_neuron_weight_thresholded, 1, &nl_v1_activation_map_neuron_weight, "");
__line = 161;
create_filter (generate_hough_activation_map, &nl_activation_map_hough, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 163;
create_filter (gaussian_filter, &nl_activation_map_hough_gaussian, 1, &nl_activation_map_hough, "%d %f", 5, 0.5);
__line = 165;
create_filter (map_image_v1, &nl_activation_map_hough_v1, 1, &nl_activation_map_hough_gaussian, "%s %f", "", LOG_FACTOR);
__line = 167;
create_filter (generate_hough_zoom_activation_map, &nl_activation_map_hough_zoom, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 169;
create_filter (gaussian_filter, &nl_activation_map_hough_zoom_gaussian, 1, &nl_activation_map_hough_zoom, "%d %f", 13, 2.0);
__line = 175;
output_connect (&nl_v1_activation_map, &out_v1_activation_map);
__line = 177;
output_connect (&nl_activation_map_hough, &out_nl_v1_activation_map_neuron_weight_thresholded);
__line = 179;
output_connect (&nl_target_coordinates, &out_target_coordinates);
__line = 181;
output_connect (&in_pattern_filtered_translated, &out_in_pattern_filtered_translated);
__line = 183;
output_connect (&table, &out_table);
__line = 185;
output_connect (&nl_activation_map_hough_zoom, &out_nl_activation_map_hough_zoom);
__line = 187;
output_connect (&nl_activation_map_hough_zoom_gaussian, &out_nl_activation_map_hough_zoom_gaussian);
__line = 193;
associate_neurons (&nl_v1_activation_map, &nl_v1_activation_map);
__line = 200;
connect_neurons (LOG, &in_pattern_filtered_translated_red, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 201;
connect_neurons (LOG, &in_pattern_filtered_translated_green, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 202;
connect_neurons (LOG, &in_pattern_filtered_translated_blue, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 206;
create_interpreter_user_function (INT_TYPE, get_target_coordinates, "get_target_coordinates", "%p %p %f");
;
__line = 207;
create_interpreter_user_function (INT_TYPE, GetImage, "GetImage", "%d");
;
__line = 208;
create_interpreter_user_function (INT_TYPE, MoveToTargetCenter, "MoveToTargetCenter", "");
;
__line = 209;
create_interpreter_user_function (INT_TYPE, CheckTrafficSignDetection, "CheckTrafficSignDetection", "");
;
__line = 210;
create_interpreter_user_function (INT_TYPE, EvaluateDetection, "EvaluateDetection", "");
;
__line = 211;
create_interpreter_user_function (INT_TYPE, ImageToRetrain, "ImageToRetrain", "");
;
__line = 212;
create_interpreter_user_function (INT_TYPE, SetScaleFactor, "SetScaleFactor", "%f");
;
__line = 213;
create_interpreter_user_function (INT_TYPE, SetImageOrder, "SetImageOrder", "%d");
;
__line = 214;
create_interpreter_user_function (INT_TYPE, SaveTLDReasultsFile, "SaveTLDReasultsFile", "");
;
__line = 215;
create_interpreter_user_function (INT_TYPE, ForwardVisualSearchNetwork, "ForwardVisualSearchNetwork", "");
;
__line = 216;
create_interpreter_user_function (FLOAT_TYPE, GetConfidence, "GetConfidence", "");
;
__line = 217;
create_interpreter_user_function (FLOAT_TYPE, GetScaleFactorInTrain, "GetScaleFactorInTrain", "");
;
__line = 218;
create_interpreter_user_function (FLOAT_TYPE, GetMinConfidenceToRetrain, "GetMinConfidenceToRetrain", "");
;
__line = 219;
create_interpreter_user_function (FLOAT_TYPE, GetConfidenceLevel, "GetConfidenceLevel", "");
;
__line = 220;
create_interpreter_user_function (INT_TYPE, GetNumPixels, "GetNumPixels", "");
;
__line = 221;
create_interpreter_user_function (INT_TYPE, GetX, "GetX", "%d");
;
__line = 222;
create_interpreter_user_function (INT_TYPE, GetY, "GetY", "%d");
;
__line = 223;
create_interpreter_user_function (FLOAT_TYPE, GetScaleBefore, "GetScaleBefore", "");
;
__line = 224;
create_interpreter_user_function (FLOAT_TYPE, GetScaleFactorZoom, "GetScaleFactorZoom", "");
;
__line = 225;
create_interpreter_user_function (INT_TYPE, GetOutOfScene, "GetOutOfScene", "");
;
__line = 226;
create_interpreter_user_function (INT_TYPE, MoveToPoint, "MoveToPoint", "%d %d");
;
__line = 227;
create_interpreter_user_function (INT_TYPE, GetX_before, "GetX_before", "%d");
;
__line = 228;
create_interpreter_user_function (INT_TYPE, GetY_before, "GetY_before", "%d");
;
__line = 229;
create_interpreter_user_function (FLOAT_TYPE, GetScaleToRetrain, "GetScaleToRetrain", "%d");
;
__line = 230;
create_interpreter_user_function (INT_TYPE, GetImageOutOfScene, "GetImageOutOfScene", "%d");
;
__line = 231;
create_interpreter_user_function (FLOAT_TYPE, GetConfidenceZoom, "GetConfidenceZoom", "");
;
__line = 232;
create_interpreter_user_function (INT_TYPE, GetDistanceZoom, "GetDistanceZoom", "");
;
__line = 233;
create_interpreter_user_function (FLOAT_TYPE, GetMaxScale, "GetMaxScale", "");
;
__line = 234;
create_interpreter_user_function (FLOAT_TYPE, GetMinScale, "GetMinScale", "");
;
__line = 235;
create_interpreter_user_function (INT_TYPE, GetNumFrames, "GetNumFrames", "");
;
__line = 236;
create_interpreter_user_function (INT_TYPE, SetOutOfScene, "SetOutOfScene", "");
;
__line = 237;
create_interpreter_user_function (INT_TYPE, DisposeMemory, "DisposeMemory", "");
;
map_layers2id (); 
count_num_neurons (); 
initialise_memory (); 
create_io_windows (); 
}
